// Generated by gencpp from file demo_02/Addints.msg
// DO NOT EDIT!


#ifndef DEMO_02_MESSAGE_ADDINTS_H
#define DEMO_02_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <demo_02/AddintsRequest.h>
#include <demo_02/AddintsResponse.h>


namespace demo_02
{

struct Addints
{

typedef AddintsRequest Request;
typedef AddintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Addints
} // namespace demo_02


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_02::Addints > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::demo_02::Addints&) { return value(); }
};

template<>
struct DataType< ::demo_02::Addints > {
  static const char* value()
  {
    return "demo_02/Addints";
  }

  static const char* value(const ::demo_02::Addints&) { return value(); }
};


// service_traits::MD5Sum< ::demo_02::AddintsRequest> should match 
// service_traits::MD5Sum< ::demo_02::Addints > 
template<>
struct MD5Sum< ::demo_02::AddintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_02::Addints >::value();
  }
  static const char* value(const ::demo_02::AddintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_02::AddintsRequest> should match 
// service_traits::DataType< ::demo_02::Addints > 
template<>
struct DataType< ::demo_02::AddintsRequest>
{
  static const char* value()
  {
    return DataType< ::demo_02::Addints >::value();
  }
  static const char* value(const ::demo_02::AddintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_02::AddintsResponse> should match 
// service_traits::MD5Sum< ::demo_02::Addints > 
template<>
struct MD5Sum< ::demo_02::AddintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_02::Addints >::value();
  }
  static const char* value(const ::demo_02::AddintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_02::AddintsResponse> should match 
// service_traits::DataType< ::demo_02::Addints > 
template<>
struct DataType< ::demo_02::AddintsResponse>
{
  static const char* value()
  {
    return DataType< ::demo_02::Addints >::value();
  }
  static const char* value(const ::demo_02::AddintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_02_MESSAGE_ADDINTS_H
